//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo foi gerado por uma ferramenta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlunoGest.aluno
{
    public partial class mensagens
    {
        protected global::System.Web.UI.WebControls.Label LblMensagem;
        protected global::System.Web.UI.WebControls.Repeater RepeaterConversas;
        protected global::System.Web.UI.WebControls.Panel PainelSemConversas;
        protected global::System.Web.UI.WebControls.TextBox TxtUsernameAmigo;
        protected global::System.Web.UI.WebControls.Button BtnAdicionarAmigo;
        protected global::System.Web.UI.WebControls.GridView GridPedidosAmizade;
        protected global::System.Web.UI.WebControls.TextBox TxtNomeGrupo;
        protected global::System.Web.UI.WebControls.CheckBoxList CheckAmigosGrupo;
        protected global::System.Web.UI.WebControls.Button BtnCriarGrupo;
        protected global::System.Web.UI.WebControls.GridView GridConvitesGrupo;
        protected global::System.Web.UI.WebControls.Label LblConversaAtual;
        protected global::System.Web.UI.WebControls.Label LblTipoConversa;
        protected global::System.Web.UI.WebControls.HiddenField HdnTipoConversa;
        protected global::System.Web.UI.WebControls.HiddenField HdnConversaId;
        protected global::System.Web.UI.WebControls.Repeater RepeaterMensagens;
        protected global::System.Web.UI.WebControls.Panel PainelSemMensagens;
        protected global::System.Web.UI.WebControls.TextBox TxtMensagem;
        protected global::System.Web.UI.WebControls.Button BtnEnviarMensagem;
    }
}
